version: "2"
services:
  app:
    build: ./app
    image: webapp
    ports:
    - "3000:3000"
    volumes: []
    links:
      - redis
    environment:
      SERVER_PORT: 3000
  redis:
    image: redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "_admin"
      POSTGRES_PASSWORD: "_password"
volumes:
  logvolume01: {}

