version: "2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "_admin"
      POSTGRES_PASSWORD: "_password"
      POSTGRES_DB: "addressbook"
    volumes:
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: api
    image: api
    container_name: nodejs_api
    depends_on:
      - db
    ports:
    - "3000:3000"
    volumes: []
    environment:
      SERVER_PORT: 3000
      PGUSER : "_admin"
      PGPASSWORD : "_password"
      PGDATABASE: "addressbook"
      PGHOST: "db"

  angular-app:
    build: app
    image: angular-app
    container_name: angular-app
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  logvolume01: {}

